// antd ConfigProvider 테마(05 문서 5.6절 + 빌드 스펙 4장). 카드 그림자 없음, 떠 있는 층만 그림자.
import type { ThemeConfig } from "antd";
import type { BrandTokens, Density } from "@/tenants/types";
import { FONT_STACK, STATUS_COLORS } from "./tokens";

export function antdTheme(t: BrandTokens, density: Density = "comfortable"): ThemeConfig {
  return {
    cssVar: true,
    hashed: false,
    token: {
      colorPrimary: t.brand,
      colorInfo: t.brand,
      colorLink: t.brand,
      colorSuccess: STATUS_COLORS.good.mark,
      colorWarning: STATUS_COLORS.warning.mark,
      colorError: STATUS_COLORS.critical.mark,
      colorErrorText: STATUS_COLORS.critical.fg,
      colorWarningText: STATUS_COLORS.warning.fg,
      colorSuccessText: STATUS_COLORS.good.fg,
      colorText: t.ink,
      colorTextHeading: t.ink,
      colorTextSecondary: t.ink2,
      colorTextTertiary: t.muted,
      colorTextQuaternary: t.muted,
      colorTextPlaceholder: t.muted,
      colorTextDescription: t.ink2,
      colorBorder: t.controlLine,
      colorBorderSecondary: t.line,
      colorSplit: t.line,
      colorBgLayout: t.panel,
      colorBgContainer: t.surface,
      colorBgElevated: t.surface,
      colorFillAlter: t.panel,
      controlItemBgHover: t.brandWeak,
      controlItemBgActive: t.brandWeak,
      fontFamily: FONT_STACK,
      fontSize: 14,
      fontWeightStrong: 600,
      borderRadius: 12,
      borderRadiusLG: 20,
      borderRadiusSM: 8,
      borderRadiusXS: 8,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      boxShadow: t.shadowPop,
      boxShadowSecondary: t.shadowPop,
      boxShadowTertiary: "none",
      motionDurationMid: "0.2s",
      motionDurationSlow: "0.2s",
      wireframe: false,
    },
    components: {
      Button: { primaryShadow: "none", defaultShadow: "none", dangerShadow: "none", fontWeight: 600, paddingInline: 18 },
      Card: { borderRadiusLG: 20, boxShadowTertiary: "none" },
      Input: { borderRadius: 10, activeShadow: "none", errorActiveShadow: "none", warningActiveShadow: "none" },
      InputNumber: { borderRadius: 10, activeShadow: "none" },
      Select: { borderRadius: 10, optionSelectedBg: t.brandWeak, optionSelectedFontWeight: 700 },
      DatePicker: { borderRadius: 10, activeShadow: "none" },
      Menu: { itemSelectedBg: t.brandWeak, itemSelectedColor: t.brand, itemBorderRadius: 12 },
      Segmented: { trackBg: t.panel, itemSelectedBg: t.surface, itemSelectedColor: t.ink, itemColor: t.ink2, borderRadius: 999, borderRadiusSM: 999, trackPadding: 4 },
      Table: {
        headerBg: t.surface, headerColor: t.ink2, rowHoverBg: t.brandWeak, borderColor: t.line,
        headerSplitColor: "transparent", cellPaddingBlock: density === "compact" ? 10 : 16, headerBorderRadius: 0,
      },
      Layout: { bodyBg: t.panel, siderBg: t.surface, headerBg: t.surface },
      Drawer: { footerPaddingBlock: 16, footerPaddingInline: 24 },
      Modal: { borderRadiusLG: 20 },
      Tabs: { inkBarColor: t.brand, itemSelectedColor: t.brand, itemActiveColor: t.brand, itemHoverColor: t.brand, titleFontSize: 14 },
      Tag: { defaultBg: t.panel, defaultColor: t.ink2, borderRadiusSM: 999 },
      Tooltip: { colorBgSpotlight: t.ink, borderRadius: 8 },
      Switch: { colorPrimary: t.brand, colorPrimaryHover: t.brand },
      Tree: { nodeSelectedBg: t.brandWeak, nodeHoverBg: t.brandWeak },
      Dropdown: { controlItemBgHover: t.brandWeak },
      Badge: { colorError: t.ink, textFontWeight: "700" },
      Calendar: { itemActiveBg: t.brandWeak },
    },
  };
}
